name: m324 AB05 A02
on:
  
  pull_request:
    branch:
      - master
    types:
      - closed
jobs:
  build-and-push-cd:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lizsalatmon/m324-ts-dockerfile:m324Tagv1

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f .k8s/namespace.yml
          kubectl apply -f .k8s/deployment.yml
          kubectl apply -f .k8s/service.yml
          kubectl apply -f .k8s/ingress.yml
